from app.models.user import User
from app.models.vehicle import Vehicle
from app.models.policy import RentalPolicy
from app.models.report import Report
from app.models.shift import Shift
from app.models.booking import Booking
from app.models.payment import Payment
from app.models.booking import Booking
from app.models.trip import Trip
from app.models.driver_assignment import DriverAssignment
from app.models.inspection import Inspection
from app.models.report import Report
from app.models.notification import Notification
