"""Add user settings

Revision ID: 05a75ca4a38a
Revises: a1b2c3d4e5f6
Create Date: 2026-09-01 08:03:37.775322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a75ca4a38a'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'email_notifications',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )
        batch_op.add_column(
            sa.Column(
                'booking_notifications',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()
            )
        )
        batch_op.add_column(
            sa.Column(
                'promotional_notifications',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                'language',
                sa.String(length=10),
                nullable=False,
                server_default='en'
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')
        batch_op.drop_column('promotional_notifications')
        batch_op.drop_column('booking_notifications')
        batch_op.drop_column('email_notifications')

    # ### end Alembic commands ###
