"""add missing user last_login column

Revision ID: 275c31245d1c
Revises: 05a75ca4a38a
Create Date: 2026-09-04 15:47:53.627715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '275c31245d1c'
down_revision = '05a75ca4a38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('return_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('return_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('driver_assignments_driver_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['driver_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_by_id'], ['id'])

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('vehicle_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('daily_rental_rate',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('daily_rental_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vehicle_type',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('registration_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('driver_assignments_driver_id_fkey'), 'drivers', ['driver_id'], ['id'])
        batch_op.drop_column('assigned_by_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('return_location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
