export const mapVehicle = (v) => ({
  ...v,
  id: v._id || v.id,
  name: v.name,
  brand: v.make || v.brand,
  category: v.vehicle_type || v.category,
  pricePerDay: v.price_per_day ?? v.pricePerDay,
  rating: v.rating,
  seats: v.seating_capacity ?? v.seats,
  doors: v.doors,
  transmission: v.transmission,
  fuelType: v.fuel_type || v.fuelType,
  luggage: v.luggage,
  location: v.location,
  image: v.image || (Array.isArray(v.images) ? v.images[0] : undefined),
  images: Array.isArray(v.images) ? v.images : [],
  features: Array.isArray(v.features) ? v.features : [],
  description: v.description,
  available: v.is_available ?? v.available,
})

export const mapBooking = (b) => ({
  ...b,
  id: b._id || b.id,
  vehicleId: b.vehicle?._id || b.vehicleId,
  driverId: b.driver?._id || b.driver_id || b.driverId,
  pickupDate: b.pickup_date || b.pickupDate,
  returnDate: b.dropoff_date || b.returnDate,
  dropoffDate: b.dropoff_date || b.dropoffDate,
  totalPrice: b.total_amount ?? b.totalPrice,
  totalAmount: b.total_amount ?? b.totalAmount,
  drivingOption: b.driving_option || b.drivingOption,
  pickupLocation: b.pickup_location || b.pickupLocation,
  dropoffLocation: b.dropoff_location || b.dropoffLocation,
  returnLocation: b.dropoff_location || b.returnLocation,
  vehicle: b.vehicle
    ? {
        ...b.vehicle,
        id: b.vehicle._id || b.vehicle.id,
        name: b.vehicle.name,
        brand: b.vehicle.make || b.vehicle.brand,
        category: b.vehicle.vehicle_type || b.vehicle.category,
        pricePerDay: b.vehicle.price_per_day ?? b.vehicle.pricePerDay,
        seats: b.vehicle.seating_capacity ?? b.vehicle.seats,
        transmission: b.vehicle.transmission,
        fuelType: b.vehicle.fuel_type || b.vehicle.fuelType,
        image: b.vehicle.image || (Array.isArray(b.vehicle.images) ? b.vehicle.images[0] : undefined),
        images: Array.isArray(b.vehicle.images) ? b.vehicle.images : [],
        features: Array.isArray(b.vehicle.features) ? b.vehicle.features : [],
        description: b.vehicle.description,
        available: b.vehicle.is_available ?? b.vehicle.available,
        location: b.vehicle.location,
      }
    : b.vehicle,
  user: b.user
    ? {
        ...b.user,
        name: b.user.name,
        email: b.user.email,
        phone: b.user.phone,
        licenseNumber: b.user.drivers_license || b.user.licenseNumber,
        licenseExpiry: b.user.license_expiry || b.user.licenseExpiry,
      }
    : b.user,
})

export const mapUser = (u) => ({
  ...u,
  id: u._id || u.id,
  name: u.name,
  email: u.email,
  phone: u.phone,
  role: u.role,
  address: u.address,
  dateOfBirth: u.date_of_birth || u.dateOfBirth,
  licenseNumber: u.drivers_license || u.licenseNumber,
  licenseType: u.license_type || u.licenseType,
  licenseIssueDate: u.license_issue_date || u.licenseIssueDate,
  licenseExpiryDate: u.license_expiry || u.licenseExpiryDate,
  licenseCountry: u.license_country || u.licenseCountry,
})

export const mapPayment = (p) => ({
  ...p,
  id: p._id || p.id,
  bookingId: p.booking?._id || p.bookingId,
  vehicle: p.booking?.vehicle?.name || p.vehicle,
  date: p.createdAt || p.date,
  method: p.method,
  amount: p.amount,
  status: p.status,
})
